# Generated by Django 5.2.15 on 2026-06-10 10:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dashboard_name', models.CharField(choices=[('executive', 'Executive Dashboard'), ('sales', 'Sales Dashboard'), ('inventory', 'Inventory Dashboard'), ('dealer', 'Dealer Dashboard'), ('crm', 'CRM Dashboard'), ('customers', 'Customer Dashboard'), ('financial', 'Financial Dashboard'), ('system_health', 'System Health Dashboard')], max_length=50)),
                ('widget_name', models.CharField(max_length=100)),
                ('position', models.IntegerField(default=0)),
                ('visibility', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='KPITracker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric_name', models.CharField(max_length=100, unique=True)),
                ('metric_value', models.DecimalField(decimal_places=4, max_digits=16)),
                ('calculated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['metric_name'], name='reports_kpi_metric__cb5d6e_idx')],
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_name', models.CharField(max_length=150)),
                ('report_type', models.CharField(choices=[('sales', 'Sales Report'), ('inventory', 'Inventory Report'), ('dealer', 'Dealer Report'), ('crm', 'CRM Report'), ('customer', 'Customer Report'), ('financial', 'Financial Report'), ('operational', 'Operational Report')], max_length=50)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('file_path', models.CharField(max_length=255)),
                ('generated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['report_type', 'generated_at'], name='reports_rep_report__952f7d_idx')],
            },
        ),
    ]
